<#
.SYNOPSIS
Switches World Mirror development branches and refreshes branch-local run assets.

.DESCRIPTION
This helper checks out a branch, determines its Minecraft version from a legacy
`minecraft_version` property or a single-target root build, cleans branch-sensitive
Fabric run caches, and downloads the matching Xaero's World Map jar through
`Get-LatestXaerosWorldMap.ps1`. On the current multi-target branch, pass
`-MinecraftVersion` explicitly.

The default clean intentionally preserves all Gradle build directories because they
contain compiled target jars under `versions/fabric-*/build/libs`. Pass `-CleanBuild`
to remove root and per-target build directories. Pass `-CleanXaeroInspectCache` to
remove `build/tmp/xaero-inspect`, the disassembly cache generated by
`Get-LatestXaerosWorldMap.ps1 -Disassemble`.

.PARAMETER CleanBuild
Remove root and per-target Gradle `build` directories. Defaults to false.

.PARAMETER CleanXaeroInspectCache
Remove `build/tmp/xaero-inspect`. Defaults to false.
#>
param(
    [Parameter(Position = 0)]
    [string]$Branch,
    [string]$MinecraftVersion,
    [string]$ModsDirectory = "run\mods",
    [string]$Loader = "fabric",
    [switch]$NoCheckout,
    [switch]$SkipClean,
    [switch]$CleanBuild,
    [switch]$CleanXaeroInspectCache,
    [switch]$SkipXaero,
    [switch]$AllowAnyXaeroGameVersion
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot

function Resolve-RepoPath {
    param([string]$Path)
    if ([System.IO.Path]::IsPathRooted($Path)) {
        return [System.IO.Path]::GetFullPath($Path)
    }
    return [System.IO.Path]::GetFullPath((Join-Path $repoRoot $Path))
}

function Assert-InRepo {
    param([string]$Path)
    $fullPath = [System.IO.Path]::GetFullPath($Path)
    $root = [System.IO.Path]::GetFullPath($repoRoot).TrimEnd('\', '/')
    if (-not ($fullPath -eq $root -or $fullPath.StartsWith($root + [System.IO.Path]::DirectorySeparatorChar))) {
        throw "Refusing to modify path outside repository: $fullPath"
    }
}

function Get-GradleProperty {
    param([string]$Name)
    $propertiesPath = Join-Path $repoRoot "gradle.properties"
    if (-not (Test-Path -LiteralPath $propertiesPath)) {
        return $null
    }
    $match = Select-String -LiteralPath $propertiesPath -Pattern "^$([Regex]::Escape($Name))=(.+)$" | Select-Object -First 1
    if ($match) {
        return $match.Matches[0].Groups[1].Value.Trim()
    }
    return $null
}

function Get-SupportedMinecraftVersions {
    $buildFile = Join-Path $repoRoot "build.gradle"
    if (-not (Test-Path -LiteralPath $buildFile)) {
        return @()
    }
    return @(Select-String -LiteralPath $buildFile -Pattern '^\s*"([^"]+)":\s*\[' |
        ForEach-Object { $_.Matches[0].Groups[1].Value })
}

function Remove-GeneratedPath {
    param([string]$RelativePath)
    $path = Resolve-RepoPath $RelativePath
    Assert-InRepo $path
    if (Test-Path -LiteralPath $path) {
        Write-Host "Removing $RelativePath"
        Remove-Item -LiteralPath $path -Recurse -Force
    }
}

Push-Location $repoRoot
try {
    if ($Branch -and -not $NoCheckout) {
        Write-Host "Switching to branch '$Branch'..."
        git switch $Branch
    } elseif (-not $Branch) {
        $Branch = (git branch --show-current).Trim()
        Write-Host "Using current branch '$Branch'."
    }

    if (-not $MinecraftVersion) {
        $MinecraftVersion = Get-GradleProperty "minecraft_version"
    }
    if (-not $MinecraftVersion) {
        $supportedVersions = @(Get-SupportedMinecraftVersions)
        if ($supportedVersions.Count -eq 1) {
            $MinecraftVersion = $supportedVersions[0]
        } else {
            throw "This branch has multiple Minecraft targets ($($supportedVersions -join ', ')). Pass -MinecraftVersion explicitly."
        }
    }

    if (-not $SkipClean) {
        if ($CleanBuild) {
            Remove-GeneratedPath "build"
            Get-ChildItem -LiteralPath (Join-Path $repoRoot "versions") -Directory -Filter "fabric-*" |
                ForEach-Object { Remove-GeneratedPath "versions\$($_.Name)\build" }
        } elseif ($CleanXaeroInspectCache) {
            Remove-GeneratedPath "build\tmp\xaero-inspect"
        }
        Remove-GeneratedPath "run\.fabric\processedMods"
        Remove-GeneratedPath "run\.fabric\remappedJars"
        Remove-GeneratedPath "run\.fabric\remappedMods"
    }

    $modsPath = Resolve-RepoPath $ModsDirectory
    Assert-InRepo $modsPath
    New-Item -ItemType Directory -Force -Path $modsPath | Out-Null

    if (-not $SkipXaero) {
        $xaeroScript = Join-Path $PSScriptRoot "Get-LatestXaerosWorldMap.ps1"
        $xaeroArgs = @{
            MinecraftVersion = $MinecraftVersion
            Loader = $Loader
            OutputDirectory = $modsPath
        }
        if ($AllowAnyXaeroGameVersion) {
            $xaeroArgs.AllowAnyGameVersion = $true
        }
        & $xaeroScript @xaeroArgs
    }

    Write-Host "Branch assets ready."
    Write-Host "Branch: $Branch"
    Write-Host "Minecraft: $MinecraftVersion"
    Write-Host "Mods: $modsPath"
} finally {
    Pop-Location
}
